### ISSUE TITLE
(Windows) Error copying configuration file: basic_ios::clear: iostream error

### ISSUE THREAD

**Issue by sakdeniz** [HorizenOfficial/zen#103]
On Windows 10 machine, daemon trying to create config file like unix folder and exiting daemon.

------------------------------------------------------------------
                        WARNING:
Automatically copying the default config file to ~/.zen/zen.conf.
This is a potential risk, as zend might accidentally compromise
your privacy if there is a default option that you need to change!

           Please restart zend to continue.
           You will not see this warning again.
------------------------------------------------------------------
Error copying configuration file: basic_ios::clear: iostream error

**Comment by tarrenj** [comment]
This was fixed in 2.0.15
