### ISSUE TITLE
Re-enable tests

### ISSUE THREAD

**Issue by tarrenj** [HorizenOfficial/zen#108]
https://github.com/ZencashOfficial/zen/blob/63e1f4ce04c20788750a03d51e49c00c67b956f7/src/gtest/test_foundersreward.cpp#L89

**Comment by cronicc** [comment]
Issue still valid, we should either adapt the disabled tests to our changed rewards, or determine if our added fork-manager tests provide enough coverage for this and remove the disabled tests.

**Comment by cronicc** [comment]
Addressed in https://github.com/ZencashOfficial/zen/pull/211
