### ISSUE TITLE
Centos 7 Build fails

### ISSUE THREAD

**Issue by christianreiss** [HorizenOfficial/zen#131]
### Describe the issue
I have been building zend on the same vm (centos7) for months now. As of today (master & v2.0.15) the build fails with configure and

```
checking for visibility attribute... yes
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)
```
It is installed:
```
rpm -qa | grep libdb
libdb4-cxx-4.8.30-13.el7.x86_64
libdb4-4.8.30-13.el7.x86_64
libdb-devel-5.3.21-24.el7.x86_64
```

#### If so, please list the steps to reproduce below:
1. Install Centos7
2. Download the sources
3. Compile

### Expected behaviour
zend is beeing build.

### Actual behaviour + errors
see above.

### The version of Zen you were using:
Zen Daemon version v2.0.14 compiled correctly.

### Machine specs:
- OS name + version: Centos 7 (updated)
- CPU: Intel(R) Xeon(R) CPU           E5620
- RAM: 16gb
- Disk size: 1tb
- Disk Type (HD/SDD): hdd
- Linux kernel version (uname -a): 3.10.0
- Compiler version (gcc -version): gcc (GCC) 4.8.5

**Comment by tarrenj** [comment]
I'll try to reproduce and find the fix later today. Thanks for reporting!

**Comment by tarrenj** [comment]
Leaving this issue open for the time being, since it's likely just a missing dependency. A PR to add the missing dependency to README.md would be a great contribution for hacktoberfest!

**Comment by tarrenj** [comment]
`zend` requires GCC 4.9 to build properly, on CentOS you can install that with:
```
sudo yum install centos-release-scl-rh
sudo yum install devtoolset-3-gcc devtoolset-3-gcc-c++
sudo update-alternatives --install /usr/bin/gcc-4.9 gcc-4.9 /opt/rh/devtoolset-3/root/usr/bin/gcc 10
sudo update-alternatives --install /usr/bin/g++-4.9 g++-4.9 /opt/rh/devtoolset-3/root/usr/bin/g++ 10
scl enable devtoolset-3 bash
```
https://zcash.readthedocs.io/en/latest/rtd_pages/user_guide.html#installation

Then run the build script (`zcutil/build.sh -j $(nproc)`)to use the correct libraries at build time.

Again, I'm leaving this issue open in the hopes that someone submits a PR to update the `README.md` file.

**Comment by christianreiss** [comment]
Hey,

did everything, "configure" fails with:

```
checking whether htobe32 is declared... yes
checking whether htobe64 is declared... yes
checking whether bswap_16 is declared... yes
checking whether bswap_32 is declared... yes
checking whether bswap_64 is declared... yes
checking for MSG_NOSIGNAL... yes
checking for visibility attribute... yes
checking for Berkeley DB C++ headers... no
configure: error: libdb_cxx headers missing, Bitcoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)
bash-4.2$ 
```

```
bash-4.2$ rpm -qa | grep libdb
libdb4-cxx-4.8.30-13.el7.x86_64
libdb4-4.8.30-13.el7.x86_64
libdb-devel-5.3.21-24.el7.x86_64
libdb-5.3.21-24.el7.x86_64
libdb-cxx-devel-5.3.21-24.el7.x86_64
libdb-5.3.21-24.el7.i686
libdb-cxx-5.3.21-24.el7.x86_64
libdb-utils-5.3.21-24.el7.x86_64
```

Thanks so far!
Interesting so far, tho, is that autogen followed by build.sh produced a binary, only configure fails.

**Comment by tarrenj** [comment]
Can you try building with the included build script please?  `./zcutil/build.sh -j $(nproc)`

**Comment by christianreiss** [comment]
Only doing the zcutil oimiting any autogen & configure produces a binary.
I guess we can close this issue.
