### ISSUE TITLE
Feature: Shared Super Node

### ISSUE THREAD

**Issue by xrow** [HorizenOfficial/zen#140]
### Describe the issue

We desired a better support for shared master nodes. Our proposed concept is open for discussion.

We envision that it might be possible that multiple t_addresses can provide each a part of the full collaterale stack for the node. Meaning the inital t_address is no longer a single value rather then a list of t_adresses that will provide the new initial balance to z_address. Rewards shall be split equally.

### Expected behaviour
Make shared nodes possible as a network feature

### Actual behaviour 
shared nodes are only possible via a outside non-enforced agreement between stack holders.

**Comment by tarrenj** [comment]
An interesting idea!  We're pretty slammed at the moment, but let's keep this issue open and see if it gets any more traction. This might be something we add in a future update.

**Comment by mauriziobinello** [comment]
Sharing of stakes is already possible with multisig addresses.
