### ISSUE TITLE
Wrong result for RPC method 'getblockfinalityindex'

### ISSUE THREAD

**Issue by alsala** [HorizenOfficial/zen#167]
In zend 2.0.17 the RPC method 'getblockfinalityindex' on some node returns huge negative values:

`$ zen-cli getblockfinalityindex $(zen-cli getbestblockhash)`
` -1073669994`

This issue might be observed when the node has been up since many weeks.

The issue has been analyzed, and the root cause is described hereafter.

The database containing the chain tips can have many fork tips of minimum length
occurred during normal operation. Unfortunately a temporary variable is not
properly sized and when the algorithm is run on old tips, integer of big
size are multiplied among them giving rise to integer overflow, which can results in negative
numbers. Since a min-operation is applied when looking for finality index, the
outcome can be the wrong result observed.

**Comment by Sto1cNate** [comment]
@cronicc @zennermac 

Problem was observed on all my nodes.

**Comment by cronicc** [comment]
Fixed in https://github.com/ZencashOfficial/zen/pull/170
