### ISSUE TITLE
CentOS 7 certificates not loaded, and false loading path used

### ISSUE THREAD

**Issue by tsujp** [HorizenOfficial/zen#168]
### Describe the issue
When running `zend` under CentOS 7 tls certificates are not loaded according to their definitions in `zen.conf`.

### Steps to reproduce
1. Compile zend
2. Enter values for `tlscertpath` and `tlscertkey` in `zen.conf`
3. Observe the daemon fail according to `debug.log` with the error below

### Expected behaviour
Tell us what should happen

### Actual behaviour + errors
```
************************
EXCEPTION: N5boost10filesystem16filesystem_errorE       
boost::filesystem::status: Permission denied: "/root/zen/depends/x86_64-unknown-linux-gnu/etc/openssl/certs"       
Zen in AppInit()
```

This directory `/root/zen` is the resultant directory of cloning the git repo, and the path only goes so far as `/root/zen/depends/x86_64-unknown-linux-gnu`. It seems strange the daemon is attempting to load certificates from a non-existent path in the source for the daemon instead of where `tlscertpath` and `tlskeypath` tell it to look. Running as `root` "fixes" this in so much as the daemon will spawn but it still doesn't load the certificates as shown by `getnetworkinfo`.

### The version of Zen you were using:
Zen Daemon version v2.0.17

### Machine specs:
- CentOS 7
- Linux CentOS-76-64-minimal 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

**Comment by PeaStew** [comment]
Please have a look here where @psyraxaus has the solution for you:

https://zen-solutions.io/loading-lets-encrypt-certificate-chain-to-the-trusted-store-on-centos/

**Comment by psyraxaus** [comment]
please try this 
Each step needs to be done even if duplicated
Can you please try running the following as this just worked on the following instance of CentOS 7

`[node@localhost` ~]$ lsb_release -a
LSB Version: :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description: CentOS Linux release 7.6.1810 (Core) 
Release: 7.6.1810
Codename: Core`

Ensure you have the ca-certificates package install

` sudo yum install ca-certificates`

Enable the dynamic CA configuration feature

` sudo update-ca-trust force-enable `

Copy the chain.pem

` sudo cp /etc/letsencrypt/live/$FQDN/chain.pem /etc/pki/ca-trust/source/anchors/`

then run

` sudo update-ca-trust extract `

and then

` sudo c_rehash `

This should then return the following when running zen-cli getnetworkinfo

  `"tls_cert_verified": true, `

I did not need to restart the zend daemon for the cert to return true using the above commands.


What I suspect is happening is that for CentOS7 the trusted store directory is not correctly looked at by the zend daemon.  By doubling up on what look like similar commands (sudo update-ca-trust extract and sudo c_rehash) the files are moved to the correct location required.

The zen/src/zen/utiltls.cpp looks at the following directories for the trusted store on linux

`#else // Linux build
    "/etc/ssl/certs",
    "/usr/local/ssl/certs",
    "/usr/lib/ssl/certs",
    "/usr/share/ssl/certs",
    "/etc/pki/tls/certs",
    "/var/lib/ca-certificates"
#endif
`
source: https://github.com/ZencashOfficial/zen/blob/e48cf6011f9220449bfb9bc2e5bdb7baf2ab18ba/src/zen/utiltls.cpp#L28

If that still fails move onto to see if  your instance was missing or had a disabled c_rehash.  install the openssl-perl package using yum

` sudo yum install openssl-perl `

Then run 

` sudo c_rehash `

You should then see  when running zen-cli getnetworkinfo

`  "tls_cert_verified": true, `

**Comment by tsujp** [comment]
After running these instructions the result is still `"tls_cert_verified": false` for the following release:

```
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core
```

**Comment by tsujp** [comment]
Attempted again as I still had my test machine up. I wiped completely and it worked. Must have been some other setting messing with this or a rogue package of some kind as both times the installation was completely fresh.
