### ISSUE TITLE
Is there a mock to replace ZEND for unit testing? 

### ISSUE THREAD

**Issue by lsmobile** [HorizenOfficial/zen#171]
Hi Everyone. 

Is there a mock to replace ZEND for unit testing? 

Thank you in advance for the answer.
Regards,
Leo S.

**Comment by cronicc** [comment]
There is no complete mock for zend per se, but extensive unit tests using gtest (including mock functionality) and rpc tests.
See https://github.com/ZencashOfficial/zen/blob/master/qa/zcash/full_test_suite.py and https://github.com/ZencashOfficial/zen/blob/master/doc/unit-tests.md.
