### ISSUE TITLE
"E: Unable to locate package zen"

### ISSUE THREAD

**Issue by thewilder** [HorizenOfficial/zen#175]
Hy there.

I'm having an issue regarding the update (2.0.17) on Digital Ocean.
After I try to download it with "sudo apt-get install zen -y", I get the following error:
"E: Unable to locate package zen"

Any help appreciated. Thanks in advance.

Peter
![Untitled](https://user-images.githubusercontent.com/30772343/60380182-1ce39100-9a39-11e9-8e06-6abbb441181b.png)

**Comment by zennermac** [comment]
Hi there

Have you added the zen repo to your apt sources and obtained and exported the gpg key for the repo?

You can see info on how to do this via looking at steps 5, 6 and 7 in this document from our official wiki.
https://horizenofficial.atlassian.net/wiki/spaces/ZEN/pages/136872094/Part+3+-+Package+Installation+and+Initial+Configuration
