### ISSUE TITLE
Disk Read/Write Specs

### ISSUE THREAD

**Issue by gaia** [HorizenOfficial/zen#183]
I am fine tuning the filesystem for running zend and would like to know the size at which read/write operations occur.

I gather that most IO demand from zend comes from R/W ops on these files:

blocks/blk000??.dat: block data (custom, 128 MiB per file)
blocks/rev000??.dat; block undo data (custom)

Is this correct? If yes, **what is the ideal disk block size to reduce the IO overhead and increase performance on a system dedicated to running zend?** I'd think something like 2MB, but these might be DB files with a smaller page size. **and are the writes synchronous or asynchronous?**

thank you

**Comment by mauriziobinello** [comment]
Hard to say. We are using LevelDB for block indexing and berkeley db for the wallet, maybe you can investigate!
