### ISSUE TITLE
Upgrading libboost from 1.66 to 1.70 breaks shielded transactions in some OpenVZ environments

### ISSUE THREAD

**Issue by cronicc** [HorizenOfficial/zen#184]
In zend 2.0.18 shielded transaction can fail if running in OpenVZ virtualization with
```
error code: -1
error message:
getrandom
```

This PR in boost 1.67 [PR#53](https://github.com/boostorg/uuid/pull/53) changes `boost::uuids::random_generator` used here https://github.com/ZencashOfficial/zen/blob/2aaf4b3bedb6eedd6e8a7a45dbc15b95bf7172b0/src/asyncrpcoperation.cpp#L17 to use OS-provided entropy directly, which is a known issue in OpenVZ where entropy is shared between all virtual environments.

We're treating this as `wontfix` for now, the solution is to use an environment that can provide sufficient entropy and has working `/dev/random` and `/dev/urandom`.

**Comment by numanWD** [comment]
Hi @cronicc,
I have currently this issue in my VPS.
The issue has started in the version `2.0.18` and I can't make transactions `z_sendmany` fail and the challenges too.

Do you know possible solutions?

**Comment by hmatejx** [comment]
I have the same issue on my nodes. 

Is there any other workaround than changing my VPS provider?
If I understand correctly, building zen from source using an older libboost would be a potential short-term workaround?

**Comment by cronicc** [comment]
We've tried installing havaged to increase available entropy in an OpenVZ VM without luck, the hoster would have to install haveged on the host. But this would still not guarantee that it works.

Reverting to libboost 1.66 and building from source would be a workaround, but we will not officially support this.

If you want to give it a try you need to edit boost.mk to look like [this](https://github.com/ZencashOfficial/zen/blob/dfb50c6b17d922bfa06a86455ce0be8caa15336e/depends/packages/boost.mk).

**Comment by numanWD** [comment]
Thanks cronicc,

I will try to build it using the source code.

About the haveged when you are refering to "Host", is my VPS provider in
the physical server right?

If I install haveged in my VPS do you think could work?
https://www.techrepublic.com/article/how-to-add-more-entropy-to-improve-cryptographic-randomness-on-linux/

Thanks

**Comment by hmatejx** [comment]
Hi cronicc, just wanted to tell you your workaround works.

Is there any major security issue accompanied by running on hosts with insufficient entropy?

**Comment by numanWD** [comment]
Awesome @hmatejx 
I was trying to compile it but I got stack with the `berkeley db` depedency ....
Could you share the compile zend and zen-cli??

Thanks

**Comment by hmatejx** [comment]
> Could you share the compile zend and zen-cli??

Sure, this was built on Ubuntu 16.04 x86_64: [zen-2.0.18-2aaf4b3-dirty-amd64.deb](https://drive.google.com/open?id=1a5kTWDOqPr09z8UvoKQOCMYG0qM_Yznj).

**Comment by numanWD** [comment]
Works perfect!!!!

Thanks so much

**Comment by hmatejx** [comment]
New workaround build for 2.0.19: [zen-2.0.19-7827af0-dirty-amd64.deb](https://drive.google.com/open?id=1-5UVZltLG699vknCMfY8dCpkgOGpdaEk)

**Comment by numanWD** [comment]
Legend!!!!

Thanks so much ;)
