### ISSUE TITLE
Delete Horizen Secure Node Block Data to Reduce Disk Occupancy

### ISSUE THREAD

**Issue by zhjgit** [HorizenOfficial/zen#186]
Horizen security node block data can be deleted, at present my cloud server disk is full, I want to delete some block data, do not know whether it will affect the operation of the security node, there is no feasible solution to reduce disk occupation?

**Comment by Sto1cNate** [comment]
@zhjgit Unfortunately no. To run a node, you must store a complete copy of the blockchain. You cannot delete any particular block data files.
