### ISSUE TITLE
Avoid ScInfoMap full copy in ScCoinsViewCache instantiation

### ISSUE THREAD

**Issue by albertog78** [HorizenOfficial/zen#213]
Current implementation of ScCoinsViewCache (https://github.com/ZencashOfficial/zen/blob/8c0712b2825152554cb6a125408b87172716e3da/src/sc/sidechain.cpp#L515) is copying the full data of ScInfoMap. 
To avoid this we should adopt an approach similar to CCoinsViewCache and CCoinsViewBacked which are keeping in memory just the "delta" operations and querying the original base in case of not having the element present in the delta. 
To follow this approach we should introduce a new abstract class ScCoinsView that should be implemented by both ScCoinsViewCache and ScMgr. ScCoinsViewCache should take as constructor  parameter a ScCoinsView base instance (in most of the cases will be the ScMgr instance). Methods of ScCoinsViewCache  should look first in the deltas and then in the ScCoinsView base instance.
Moreover the Flush implementation of ScCoinsViewCache should delegate to a single method of the base for batch update (see how CCoinsViewCache::Flush() is implemented)

**Comment by abi87** [comment]
I believe the issue as described above has been solved in branch sc_undo_code_unit_test , commit 457808852aa77f600bae9b576a1453d5baae56e4
I am going to track the work required to coalesce the class hierarchies of  ScCoinsViewCache  with CCoinsViewCache and other related into issue https://github.com/ZencashOfficial/zen/issues/215
@albertog78 if you agree with this choice, you can close the current issue.
