### ISSUE TITLE
Undocumented dependency for Regression tests

### ISSUE THREAD

**Issue by abi87** [HorizenOfficial/zen#217]
Hello,
I tried to run the test qa/rpc-tests/prioritisetransaction.py on Ubuntu 18.04.3 LTS with Python 2.7.17 and the test fails.

The stack trace indicates a dependency is missing, namely pyblake2. Here you are the stack trace
=== Running testscript prioritisetransaction.py ===
Traceback (most recent call last):
  File "/home/abenegia/Work/zen_ut_sc/qa/rpc-tests/prioritisetransaction.py", line 9, in <module>
    from test_framework.mininode import COIN
  File "/home/abenegia/Work/zen_ut_sc/qa/rpc-tests/test_framework/mininode.py", line 33, in <module>
    from pyblake2 import blake2b
ImportError: No module named pyblake2
!!! FAIL: prioritisetransaction.py !!!

The issue is easily fix installing pyblake2. 
I just wonder whether we should document this somewhere.
Thanks
Alberto

**Comment by cronicc** [comment]
Yes, this belongs in README.md.

**Comment by abi87** [comment]
Thank you @cronicc . I kept testing and realized there is a similar issue with pyzmq module, which is a undeclared dependency for qa/rpc-tests/zmq_test.py 

Sorry if I missed this before.
