### ISSUE TITLE
EXCEPTION: St12out_of_range

### ISSUE THREAD

**Issue by RakibFiha** [HorizenOfficial/zen#239]
### Actual behaviour + errors
The Zend daemon repeatedly restarts with following init message:
```
EXCEPTION: St12out_of_range
map::at
Zen in AppInit()
```

### The version of Zen:
Zen Daemon version v2.0.20
### Machine specs:
- OS name + version: Ubuntu 18.04
- CPU: rockpi 64
- RAM: 4 GB
- Disk size: 64 GB
- Disk Type (HD/SDD): SDD
- Linux kernel version (uname -a): Linux neuxa080048 4.4.154-59-rockchip-g5e70f14 #4 SMP Fri Dec 14 20:55:41 CST 2018 aarch64 aarch64 aarch64 GNU/Linux
- Compiler version (gcc -version): gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by cronicc** [comment]
Resolved after a conversation on Discord, issue was a corrupted wallet.dat.
