### ISSUE TITLE
Alert key needs to be changed.

### ISSUE THREAD

**Issue by tarrenj** [HorizenOfficial/zen#32]
None of the current team members have a copy of the private key required for sending alerts. What's more, the state of this key is unknown and may be compromised.

A new key is required.

**Comment by tarrenj** [comment]
I'm getting started on this now.

**Comment by tarrenj** [comment]
New private key has been generated and sent (via encrypted email) to cronic.  Generating new test data now.

**Comment by cronicc** [comment]
Key received and stored safely.
