### ISSUE TITLE
cb-no-community-fund ERROR message

### ISSUE THREAD

**Issue by seperatis** [HorizenOfficial/zen#340]
When trying to set up my mining pool to support mining Horizen, I am getting the following error when submitting a block.

`error cb-no-community-fund`

Can anyone tell me what this error means and how to possibly correct this? I'm looking forward to adding Zen mining to my pool.

Thanks everyone!

**Comment by cronicc** [comment]
Hi @seperatis 

in Horizen every coinbase transaction has to include vouts that send 20% of the block reward to the community fund address, 10% of the rewards to the secure node address and 10% of the reward to the super node address.

An example of how this is handled in node-stratum-pool can be found here https://github.com/s-nomp/node-stratum-pool/blob/b36b7792aec3a85b9e5fd03c0798d97c7eb445a1/lib/transactions.js#L76-L130

The addresses can be found here https://github.com/HorizenOfficial/zen/blob/2a5e4bc40180bbcb72a0fdc003a52b6812301d98/src/zen/forks/fork4_nulltransactionfork.cpp#L10-L38

`zen-cli getblocktemplate` also includes the amounts that have to be sent:
```
[...]
  "coinbasetxn": {
    "data": "01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff0503d2810c00ffffffff04703fdd2c000000001976a9140f774acde172ba5ce1cf1a7a7303747dd7beee7b88ac80b2e60e0000000017a914df23c5eaba30b4d95798c5d5d0e2ecc2a3dc4ff287405973070000000017a914c5d4ea3a50a897f0a62b4c3716b9a74335f350bf87405973070000000017a914561dfaa957a6fada76137d3ac1b9ba9920768c718700000000",
    "hash": "97e4eff2ea06f79d653fc4f267185a9c71d572ea64134de2a4283ef8be8e84e1",
    "depends": [
    ],
    "fee": -2697200,
    "sigops": 1,
    "communityfund": 250000000,
    "securenodes": 125000000,
    "supernodes": 125000000,
    "required": true
  },
[...]
```

**Comment by seperatis** [comment]
Thank you! Closing this.
