### ISSUE TITLE
RPC time out

### ISSUE THREAD

**Issue by ruyichang** [HorizenOfficial/zen#346]
Hi,Recently, I have found that time out frequently appears in both GeblockTemplate and Submit.

 Server responded with code: 500.

 And my node hardware configuration is 8c 16G.

Is there an option to optimize Time Out in the zen.conf configuration file? Thank you.

**Comment by cronicc** [comment]
Hi @ruyichang 

setting higher values with the following options can help with RPC performance.
```
  -rpcthreads=<n>
       Set the number of threads to service RPC calls (default: 4)

  -rpcworkqueue=<n>
       Set the depth of the work queue to service RPC calls (default: 16)

  -rpcservertimeout=<n>
       Timeout during HTTP requests (default: 30)
```

Additionally disabling the wallet on the stratum node zend instance can help with improving performance.
```
-disablewallet -mineraddress=someaddress -minetolocalwallet=0
```

**Comment by ruyichang** [comment]
@cronicc Thank you, i'll try this options and i want to try -blockmaxsize/-blockprioritysize/-blockmaxcomplexity to avoid too much TXs in a block.Do you have any good suggestions about TXs and block size？

**Comment by cronicc** [comment]
Hi @ruyichang 

if you're using s-nomp/node-stratum-pool, the first performance optimization I'd suggest to you would be to enable blocknotify (https://github.com/s-nomp/s-nomp#optional-recommended-setting-up-blocknotify), and then disable block polling or increase the polling interval.

With the default config s-nomp polls the stratum daemon over RPC for updated blocktemplates every half second. IIRC this is done for each pool thread, so if you have multiple threads with `options.clustering.forks: "auto"` set this can mean many RPC calls per second. Polling can be disabled by setting https://github.com/s-nomp/s-nomp/blob/7fdba6464fecf3a57ecba65624acf3028f8b0c30/config_example.json#L14 to 0.

There are some instances where RPC commands can "block" in zend, one of these is receiving a large block and updating chaintip. Any time this happens new RPC calls would be queued up, potentially running into timeouts or the RPC queue limit.

To reduce the amount of time it takes for zend to accept new blocks, not only high IPC CPU performance is important, but also fast SSD storage.

A known performance issue with 'getblocktemplate' calls is when transactions with many transparent inputs are in the memory pool. Validating transactions for inclusion in the block template scales quadratically with the number of vin per transaction.

For this reason the `-blockmaxcomplexity` switch was introduced, from `zend -help`:
```
  -blockmaxcomplexity=<n>
       Limit transactions to be included into blocks based on block complexity.
       Block complexity is the sum of transaction complexity per block.
       Transaction complexity is the number of inputs of a transaction squared.
       Like -mempooltxinputlimit this switch is intended as a last resort when
       unable to build blocks fast enough because of poor GBT performance. 0 or
       negative values means no limit is applied. (default: 0)
```
Setting `-blockmaxcomplexity` would be my only recommended method to increase getblocktemplate performance, as using other methods like `-blockmaxsize` greately reduces the overall transaction throughput of the blockchain (which we're already seeing with one large pool at the moment).

A good starting value would be `-blockmaxcomplexity=300000`, as this shouldn't be limiting under normal circumstances.
Some example calculations, a single large transaction close to the 100kB tx size limit with 500 vin has a complexity of `500 * 500 = 250000`, which would be equivalent to 10000 transactions with 5 vin each `5 * 5 * 10000 = 250000`.

We still would prefer pools not limiting at all, as low  `-blockmaxcomplexity` values applied across all pools could mean high complexity transactions would never get included in blocks.

So please try to start off with the performance tuning tips if you use s-nomp, and if that doesn't help set  `-blockmaxcomplexity`  to very high values at first to see if it makes a difference.

**Comment by hashbender** [comment]
Creating an empty job + block template to mine during the initial GBT for a new height is about the best you can do.

**Comment by ruyichang** [comment]
@cronicc @nitronick600 Got that, thanks.
