### ISSUE TITLE
Reindex performance issue

### ISSUE THREAD

**Issue by albertog78** [HorizenOfficial/zen#347]
Reindex operation seems really slow even compared to full download. We should verify if reindex is also performing the whole consistency checks even if the chain is synced after a checkpoint (during download such checks are not performed if a checkpoint was present). For backward compatibility, an option would be to introduce a new switch (eg. fast_reindex) that skips the "heavy" checks before checkpoints if already synced after that point (use same logic of download phase).

**Comment by cronicc** [comment]
Closed with https://github.com/HorizenOfficial/zen/commit/e109c9ae9395048febb23d41420665371bfe927b

`-reindexfast` added addressing this issue
