### ISSUE TITLE
zend output

### ISSUE THREAD

**Issue by tarrenj** [HorizenOfficial/zen#35]
Currently, `zend` outputs a line telling users to check the ZCash security page for information.  This has been removed in `zen/master`.  The commit where it was last changed is https://github.com/ZencashOfficial/zen/commit/3b0715dd37b85a37611ab2cfcd6148bb17d551cc#diff-b7702a084eb00fb47f9800fd68271951

I'd like to `cherry-pick` the changes in (visable here: https://github.com/ZencashOfficial/zencash/commit/df9a7467c0ae26116a592451f6cc93caa372e1f9), but I think part of the goal was removing the previous devs work from our commit tree.

How should I proceed?

**Comment by tarrenj** [comment]
The same user is responsible for the commit where the URL is changed from the ZCash one to our old URL.  So `cherry-pick`ing that would present the same issue.

**Comment by tarrenj** [comment]
I've been asked to just create a new commit in Discord.

**Comment by pierstab** [comment]
agree , create a new commit its better
