### ISSUE TITLE
Signed transaction failed to be sent, does Zen have an example of signing? What parameters are required

### ISSUE THREAD

**Issue by hzccc** [HorizenOfficial/zen#356]
Signed transaction failed to be sent, does Zen have an example of signing? What parameters are required

**Comment by cronicc** [comment]
@hzccc how are you trying to sign a transaction? In general our BIP-115 replay protection introduced some changes to transaction signing vs zcash/bitcoin transparent transactions.

We have a Javascript library that fully supports P2PKH and P2SH transaction signatures here https://github.com/HorizenOfficial/zencashjs.
