### ISSUE TITLE
How do i withdraw my earned ZEN from my Zen wallet ?

### ISSUE THREAD

**Issue by koe12** [HorizenOfficial/zen#388]
How do i withdraw my earned ZEN from my Zen wallet ?

_Originally posted by @WNIOhai in https://github.com/HorizenOfficial/zencash-mobile/issues/114#issuecomment-774137595_

**Comment by ptagl** [comment]
Hi @koe12, sorry for the late reply. I hope you already solved the issue with your wallet, if it's not the case, please, feel free to contact our Support Team on Discord, they will be happy to help you out!
