### ISSUE TITLE
Fees not involved in Json Structure

### ISSUE THREAD

**Issue by debasish22** [HorizenOfficial/zen#389]
Block - 946957

TransactionHashes :
258ac0a7701d8fe3a7f86cfcdabe971d6710ad447db7d66125fd5777803f9137 
efbbfb4808972baf400e272be7edf53a87e95ef07f15acad98397edfdf6b32ef
8f89f9fe7b025f3c0cbf5b1131b1b8b66b3ef95b84d1257b8393b385d4e3930a
eb7572eb7104735f36094590ef6f1793b283c583160d0eb4797f6c198d34ce74 

From  the above hashes when we sum up all the Vins and Vouts there is a difference of the fees which is not included in the json structure . how can i get the fees separately

**Comment by ptagl** [comment]
Hi @debasish22, sorry for the late reply.

I guess that what you meant is that if you try to call the RPC command `getrawtransaction`, you get the list of inputs and outputs but there isn't any `fee` field and thus the computation has to be done manually.

If this is what you're asking, there is no way to include fees in `getrawtransaction` as it's intended to decode the "raw" transaction without providing any additional computed information. There are other RPC commands like `gettransaction` or `listtxesbyaddress` that include the fee in the JSON response, but they only work for transactions that are included in the local wallet.

If you really need to get the fees without computing them manually, the only solution that comes to my mind is to use the JSON response from the `tx` Explorer API, for instance [https://explorer.horizen.io/api/tx/258ac0a7701d8fe3a7f86cfcdabe971d6710ad447db7d66125fd5777803f9137](https://explorer.horizen.io/api/tx/258ac0a7701d8fe3a7f86cfcdabe971d6710ad447db7d66125fd5777803f9137).

Please, let me know if you have any further question!
