### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by bimmerv** [HorizenOfficial/zen#390]
Hi.
Today I received emails, that two my nodes had status:` Certificate has expired `(in UI)
I checked certificates on my nodes and letsencrypt said:
 ```
   Domains: bimzen2.zloy.xyz
    Expiry Date: 2021-10-30 05:07:18+00:00 (VALID: 29 days)
    Domains: bimzen.zloy.xyz
    Expiry Date: 2021-11-04 05:01:03+00:00 (VALID: 34 days)
```
But 
`zen-cli getnetworkinfo`
said:
`  "tls_cert_verified": false`

I have checked the path to certificates, restart zend but nothing helps.
Can someone help me to debug this issue?
Thanks

**Comment by kiliansitel** [comment]
Hi,

I think this issue is due to https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

DST Root CA X3 will expire on September 30, 2021. That means those older devices that don’t trust ISRG Root X1 will start getting certificate warnings when visiting sites that

**Comment by cronicc** [comment]
https://zen-solutions.io/how-to-fix-r3-expired-lets-encrypt-certificates-on-nodes/

**Comment by bimmerv** [comment]
thanks guys! your links resolved my problem!
