### ISSUE TITLE
API call "getnetworkinfo" returns help command output instead as an error

### ISSUE THREAD

**Issue by paintballrefjosh** [HorizenOfficial/zen#395]
### Describe the issue
On all of my nodes when using the API with the command "getnetworkinfo" via curl it returns what appears to be the "help getnetworkinfo" output under the "error" value in the JSON string.

#### If so, please list the steps to reproduce below:
1.  curl --user myuser --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getnetworkinfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/

### Expected behaviour
Should get output that is in line with the CLI command:

> `user@zen-node01:~$ zen-cli getnetworkinfo
> {
>   "version": 2002350,
>   "subversion": "/zen:2.0.23/",
>   "protocolversion": 170002,
>   "localservices": "0000000000000001",
>   "timeoffset": 0,
>   "connections": 36,
>   "tls_cert_verified": true,
>   "networks": [
>     {
>       "name": "ipv4",
>       "limited": false,
>       "reachable": true,
>       "proxy": "",
>       "proxy_randomize_credentials": false
>     },
>     {
>       "name": "ipv6",
>       "limited": false,
>       "reachable": true,
>       "proxy": "",
>       "proxy_randomize_credentials": false
>     },
>     {
>       "name": "onion",
>       "limited": true,
>       "reachable": false,
>       "proxy": "",
>       "proxy_randomize_credentials": false
>     }
>   ],
>   "relayfee": 0.00000100,
>   "localaddresses": [
>     {
>       "address": "2001:470:1f0f:4f7::22",
>       "port": 9033,
>       "score": 168
>     }
>   ],
>   "warnings": ""
> }`

### Actual behaviour + errors
Returns the data as an error and appears to be the output from "help getnetworkinfo" instead of just "getnetworkinfo"

> `curl --user myuser --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getnetworkinfo", "params": [5] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/
> Enter host password for user 'myuser':
> {"result":null,"error":{"code":-1,"message":"getnetworkinfo\nReturns an object containing various state info regarding P2P networking.\n\nResult:\n{\n  \"version\": xxxxx,                      (numeric) the server version\n  \"subversion\": \"/MagicBean:x.y.z[-v]/\",     (string) the server subversion string\n  \"protocolversion\": xxxxx,              (numeric) the protocol version\n  \"localservices\": \"xxxxxxxxxxxxxxxx\", (string) the services we offer to the network\n  \"timeoffset\": xxxxx,                   (numeric) the time offset (deprecated; always 0)\n  \"connections\": xxxxx,                  (numeric) the number of connections\n  \"tls_cert_verified\": true|flase,       (boolean) true if the certificate of the current node is verified\n  \"networks\": [                          (array) information per network\n  {\n    \"name\": \"xxx\",                     (string) network (ipv4, ipv6 or onion)\n    \"limited\": true|false,               (boolean) is the network limited using -onlynet?\n    \"reachable\": true|false,             (boolean) is the network reachable?\n    \"proxy\": \"host:port\"               (string) the proxy that is used for this network, or empty if none\n  }\n  ,...\n  ],\n  \"relayfee\": x.xxxxxxxx,                (numeric) minimum relay fee for non-free transactions in ZEN/kB\n  \"localaddresses\": [                    (array) list of local addresses\n  {\n    \"address\": \"xxxx\",                 (string) network address\n    \"port\": xxx,                         (numeric) network port\n    \"score\": xxx                         (numeric) relative score\n  }\n  ,...\n  ]\n  \"warnings\": \"...\"                    (string) any network warnings (such as alert messages) \n}\n\nExamples:\n> zen-cli getnetworkinfo \n> curl --user myusername --data-binary '{\"jsonrpc\": \"1.0\", \"id\":\"curltest\", \"method\": \"getnetworkinfo\", \"params\": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/\n"},"id":"curltest"}`

### The version of Zen you were using:
v2.0.23

### Machine specs:
- OS name + version: Ubuntu 20.04.3 LTS
- CPU: 4 cores of Intel Xeon E5-2650 V4 or similar
- RAM: 3GB
- Disk size: 100GB
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): Linux hostname 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Compiler version (gcc -version): gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

### Any extra information that might be useful in the debugging process.
Using the provided .deb files from the latest release.

### Do you have a back up of `~/.zen` directory and/or take a VM snapshot?
Yes I can take a snapshot

**Comment by cronicc** [comment]
Hi, I just tested the command with curl and it works
```
curl --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getnetworkinfo", "params": [] }' -H 'content-type: text/plain;' http://user:password@127.0.0.1:8231/
```

In your example you have `"params": [5]`, please make sure params is an empty array as getnetworkinfo takes no arguments.

**Comment by paintballrefjosh** [comment]
Thanks Cronicc.  I did verify mine is working now.  Not sure how the "5" got in there but you are correct.  Sorry for the false alarm.
