### ISSUE TITLE
apt cache not updating only with Zen repo

### ISSUE THREAD

**Issue by fabioganga** [HorizenOfficial/zen#396]
## Describe the issue
As suggested in the official Telegram channel, I am reporting this strange issue which is affecting me. 

I am running an Ubuntu 18.04.3 VPS on Intel x64 architecture (Intel  Xeon D-1540 8c / 16t). 

After having followed all the steps to add the official Horizen repo and updating the apt cache, I get

root@s0:/# apt-get install zen -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package zen

  
### Expected behaviour
The package should be found and installed.

### Machine specs:
- OS name + version: Ubuntu 18.04.3 LTS
- CPU: Intel  Xeon D-1540 8c / 16t
- RAM: 8 GB
- Disk size: 200 GB
- Disk Type (HD/SDD): HD
- Linux kernel version (uname -a): 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:12:19 UTC 2018 i686 i686 i686 GNU/Linux
- Compiler version (gcc -version): gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Please note that adding another repo for test has proven to be successful and the apt cache does get updated, I only get this issue with the zen repo**. 

Many thanks for your help!

**Comment by cronicc** [comment]
Hi, lets make sure you've correctly added the apt repo and clear the package cache.

Please do the following:
```
sudo apt-get update
sudo apt-get install -y apt-transport-https lsb-release

echo 'deb https://HorizenOfficial.github.io/repo/ '$(lsb_release -cs)' main' | sudo tee /etc/apt/sources.list.d/zen.list
gpg --batch --keyserver ha.pool.sks-keyservers.net --recv 219F55740BBF7A1CE368BA45FB7053CE4991B669 || \
gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 219F55740BBF7A1CE368BA45FB7053CE4991B669 || \
gpg --batch --keyserver pgp.mit.edu --recv 219F55740BBF7A1CE368BA45FB7053CE4991B669 || \
gpg --batch --keyserver keyserver.pgp.com --recv 219F55740BBF7A1CE368BA45FB7053CE4991B669 || \
gpg --batch --keyserver pgp.key-server.io --recv 219F55740BBF7A1CE368BA45FB7053CE4991B669
gpg --export 219F55740BBF7A1CE368BA45FB7053CE4991B669 | sudo apt-key add -

sudo rm /var/lib/apt/lists/*
sudo apt-get update
sudo apt-get install zen
```

**Comment by fabioganga** [comment]
Hi @cronicc and thanks so much for your quick reply.

I run the commands you gave me, which were accepted successfully, apart from the gpg keys step which comes up with the following result:

root@s0:~# gpg --batch --keyserver ha.pool.sks-keyservers.net --recv 219F55740BBF7A1CE368BA45FB7053CE4991B669 || \
> gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 219F55740BBF7A1CE368BA45FB7053CE4991B669 || \
> gpg --batch --keyserver pgp.mit.edu --recv 219F55740BBF7A1CE368BA45FB7053CE4991B669 || \
> gpg --batch --keyserver keyserver.pgp.com --recv 219F55740BBF7A1CE368BA45FB7053CE4991B669 || \
> gpg --batch --keyserver pgp.key-server.io --recv 219F55740BBF7A1CE368BA45FB7053CE4991B669
gpg: keyserver receive failed: No name
gpg: keyserver receive failed: No name
gpg: key FB7053CE4991B669: "cronic <cronic@horizen.io>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
root@s0:~# gpg --export 219F55740BBF7A1CE368BA45FB7053CE4991B669 | sudo apt-key add -
OK

Also, I need to add -Rfv in order to remove the lists, as follows:

root@s0:~# rm -Rfv /var/lib/apt/lists/*
removed directory '/var/lib/apt/lists/auxfiles'
removed directory '/var/lib/apt/lists/partial'
root@s0:~#

The rest was executed nicely with no errors.

Despite all of this, I am still receiving

root@s0:~# apt-get install zen -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package zen
root@s0:~#

Thanks.

Kind Regards,
Fabio

**Comment by fabioganga** [comment]
For your own information, I am also running a test on a separate VPS server, on exactly the same hardware, but with Ubuntu 20 rather than Ubuntu 18.

That environment is fine, zend is installed nicely and runs.

The issue seems to be affecting, in my case, only Ubuntu 18.

Thanks

**Comment by cronicc** [comment]
I've just tried with a bionic docker container and all works fine there. 

Did you get any errors when running `apt-get update`?
Please make sure you've also installed `ca-certificates` as this is needed for https to work with apt.

`apt-get policy zen` should show the zen package as well.

**Comment by fabioganga** [comment]
@cronicc 

My apologies for the delay in replying.

You'd never believe it... I accidentally had downloaded and installed a 32 bit installation template instead of a 64 bits one for my VPS.

I rebuilt it as a 64 bit and it works seamlessly as it should.

Many thanks for your support, much appreciated buddy!

Kind Regards,
Fabio

**Comment by cronicc** [comment]
I could have noticed the  i686 output in uname as well, but glad you solved it.
