### ISSUE TITLE
New Version v2.0.24 

### ISSUE THREAD

**Issue by room101-dev** [HorizenOfficial/zen#398]
No warning about upgrade to ubuntu 18 when running 'apt update/upgrade', just silent fail 

Stay's at zend ver 23

Once you 'force' a ubuntu upgrade to 'bionic'  ( 16.0 to 18.0 forced 'push/pull' operation ), multiple forced requests required.

Then the 'apt upgrade' finds the new version, only after the (/etc/sources) zen.list files are edited to bionic. 'sed /.../bionic/g zen.list'

Past documentation model was that 'apt update/upgrade' was default, the new 'dev' person seems to think that 'git clone' or 'dpkg -i' is the default method. I'm leary of putting blind faith in unknown github sources, easily faked. With all the security on Horizen, one would think the 'apt update/upgrade' would be default, given Horizen control of proper source depository location signed by valid signature.

**Comment by cronicc** [comment]
Hi @room101-dev , the apt repo has been updated and does include 2.0.24. We've clearly stated in our email that support for older distributions has been discontinued, which could be why you're not seeing v2.0.24 after doing an apt-get update.

**Comment by room101-dev** [comment]
closed
