### ISSUE TITLE
upgrading from 2.0.23 to 2.0.24 is causing issues 

### ISSUE THREAD

**Issue by debasish22** [HorizenOfficial/zen#399]
This is the first time i have got this issue with horizen node . So below is the folder structure i have 

node-horizen (Parent folder)

docker-compose.yaml
node-horizen-dockerfile- entrypoint.sh  dockerfile
docker-compose.yaml

change in dockerfile - ARG version=2.0.24-bitcore and then sudo docker build .

Then i get the below errors. Please find screenshots attached. Any help here please
<img width="774" alt="Horizen-NodeIssue2" src="https://user-images.githubusercontent.com/30689502/139796572-4274a974-c88d-49c5-b0bc-24827100bbda.PNG">
<img width="769" alt="Horizen-NodeIssue" src="https://user-images.githubusercontent.com/30689502/139796599-e6a4353c-069f-4345-bf66-5b0d3c327907.PNG">

**Comment by cronicc** [comment]
Hi @debasish22 

SKS Keyservers are gone now, you'll have to use different servers to fetch the keys, see https://unix.stackexchange.com/questions/656205/sks-keyservers-gone-what-to-use-instead.

I recommend using keys.openpgp.org (where I have verified my key, so the identity signing zend releases is available there) or keyserver.ubuntu.com which still seems to be working.

**Comment by NightDog** [comment]
Then I'd kindly suggest someone update the commands at: https://horizenofficial.github.io/repo/ they still point to that keyserver. Just hit this myself :)
Edit: And the suggestion of using keys.openpgp.org worked perfectly btw.

**Comment by cronicc** [comment]
@NightDog done https://github.com/HorizenOfficial/repo/commit/a21d921c8df55e31267d8927bff0eaaf7c61a735

**Comment by NateBoogie24** [comment]
sudo apt-get install \
      build-essential pkg-config libc6-dev m4 g++-multilib \
      autoconf libtool ncurses-dev unzip git python \
      zlib1g-dev bsdmainutils automake curl
