### ISSUE TITLE
Zend not starting after upgrade from 2.0.24 tot 3.0.1

### ISSUE THREAD

**Issue by rtdegraaf** [HorizenOfficial/zen#408]
After upgrading ZEN via apt the zend.service wont start. Journalctl is showing:

-- Unit zend.service has begun starting up.
Nov 18 11:22:01 zen zend[3515]: Zen server starting
Nov 18 11:22:01 zen systemd[1]: zend.service: Can't open PID file /home/ronald/.zen/zend.pid (yet?) after start: No such file or directory
Nov 18 11:23:32 zen systemd[1]: zend.service: Start operation timed out. Terminating.
Nov 18 11:23:32 zen systemd[1]: zend.service: Failed with result 'timeout'.
Nov 18 11:23:32 zen systemd[1]: Failed to start Zen daemon.
-- Subject: Unit zend.service has failed

Creating zend.pid manualy does not solve this isseu. The zentracker service is starting whitout any problems. /var/log/syslog and zen debug log  is not showing any clue's. Any idea's?

OS: Ubuntu Bionic (18.04)

Config file:
rpcuser=xxx
rpcpassword=xxx
rpcport=18231
rpcallowip=127.0.0.1
rpcworkqueue=512
server=1
daemon=1
listen=1
txindex=1
logtimestamps=1
#testnet config
#testnet=1
tlscertpath=/etc/letsencrypt/live/hostname/cert.pem
tlskeypath=/etc/letsencrypt/live/hostname/privkey.pem
externalip=1.2.3.4
port=9033

**Comment by cronicc** [comment]
Hi @rtdegraaf 

please run this
```
( grep -q "adx" /proc/cpuinfo && grep -q "bmi2" /proc/cpuinfo ) &&
echo "v3.0.1 supported" ||
echo "v3.0.1 NOT supported"
```

If you see `v3.0.1 NOT supported` printed on the console your CPU is too old to install the packages provided by the APT repository. For that case we're providing alternative packages on github for legacy CPUs. To install please run the following:
```
sudo systemctl stop zend; cd ~/ &&
wget https://github.com/HorizenOfficial/zen/releases/download/v3.0.1/zen-3.0.1-legacy-cpu-amd64.deb &&
wget https://github.com/HorizenOfficial/zen/releases/download/v3.0.1/zen-3.0.1-legacy-cpu-amd64.deb.sha256 &&
sha256sum -c zen-3.0.1-legacy-cpu-amd64.deb.sha256 &&
sudo dpkg -i zen-3.0.1-legacy-cpu-amd64.deb &&
rm zen-3.0.1-legacy-cpu-amd64.deb* &&
sudo systemctl start zend
```

**Comment by rtdegraaf** [comment]
Thanks @cronicc, that worked, great! The zend service is up and running again. :)
