### ISSUE TITLE
Unable to build / bzip issues

### ISSUE THREAD

**Issue by christianreiss** [HorizenOfficial/zen#421]
### Describe the issue
Source does not build in a fresh, clean installation of AlmaLinux (Redhat, CentOs...)

### Can you reliably reproduce the issue?
Yes.

#### If so, please list the steps to reproduce below:
1.  Install a fresh CentOS/RedHat/AlmaLinux/RockyLinux 8
2.  Update to current, install required dev packages.
3. Try building.

### Expected behaviour
I have a zend binary.

### Actual behaviour + errors
Build fails with

```
/root/zen-3.0.2-bitcore/depends/x86_64-unknown-linux-gnu/share/../lib/libzendoo_mc.a(bzip2-a63c95899f3f4602.bzip2.f2t43t27-cgu.0.rcgu.o): In function `bzip2::mem::Compress::new':
bzip2.f2t43t27-cgu.0:(.text._ZN5bzip23mem8Compress3new17h241f87b574301034E+0x7c): undefined reference to `BZ2_bzCompressInit'
/root/zen-3.0.2-bitcore/depends/x86_64-unknown-linux-gnu/share/../lib/libzendoo_mc.a(bzip2-a63c95899f3f4602.bzip2.f2t43t27-cgu.0.rcgu.o): In function `bzip2::mem::Compress::compress':
bzip2.f2t43t27-cgu.0:(.text._ZN5bzip23mem8Compress8compress17h43e92e79884f8df4E+0x3a): undefined reference to `BZ2_bzCompress'
/root/zen-3.0.2-bitcore/depends/x86_64-unknown-linux-gnu/share/../lib/libzendoo_mc.a(bzip2-a63c95899f3f4602.bzip2.f2t43t27-cgu.0.rcgu.o): In function `bzip2::mem::Compress::compress_vec':
bzip2.f2t43t27-cgu.0:(.text._ZN5bzip23mem8Compress12compress_vec17h072f7c83778c3151E+0x5d): undefined reference to `BZ2_bzCompress'
/root/zen-3.0.2-bitcore/depends/x86_64-unknown-linux-gnu/share/../lib/libzendoo_mc.a(bzip2-a63c95899f3f4602.bzip2.f2t43t27-cgu.0.rcgu.o): In function `bzip2::mem::Decompress::new':
bzip2.f2t43t27-cgu.0:(.text._ZN5bzip23mem10Decompress3new17h5d95079b0655282bE+0x76): undefined reference to `BZ2_bzDecompressInit'
/root/zen-3.0.2-bitcore/depends/x86_64-unknown-linux-gnu/share/../lib/libzendoo_mc.a(bzip2-a63c95899f3f4602.bzip2.f2t43t27-cgu.0.rcgu.o): In function `bzip2::mem::Decompress::decompress':
bzip2.f2t43t27-cgu.0:(.text._ZN5bzip23mem10Decompress10decompress17he19727db7f3e8d6cE+0x23): undefined reference to `BZ2_bzDecompress'
/root/zen-3.0.2-bitcore/depends/x86_64-unknown-linux-gnu/share/../lib/libzendoo_mc.a(bzip2-a63c95899f3f4602.bzip2.f2t43t27-cgu.0.rcgu.o): In function `bzip2::mem::Decompress::decompress_vec':
bzip2.f2t43t27-cgu.0:(.text._ZN5bzip23mem10Decompress14decompress_vec17h266922c54275cfafE+0x48): undefined reference to `BZ2_bzDecompress'
```
The output is actually much much longer (more fails below, but this is the root cause.)

### The version of Zen you were using:
zen-3.0.2-bitcore

### Machine specs:
- OS name + version: AlmaLinux 8 
- CPU: Skylake 
- RAM: 32gb
- Linux kernel version (uname -a): 4.18.0-348.2.1.el8_5.x86_64
- Compiler version (gcc -version): gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)

### Misc
The build succeeds when using Dockerfile below. Huh.

**Comment by cronicc** [comment]
Hi @christianreiss 

It would be very helpful for debugging if you could provide a Dockerfile based on https://hub.docker.com/_/almalinux with all build dependencies installed so that we can replicate your environment. Although we strive for wide compatibility it's not always possible to test all environments.

**Comment by christianreiss** [comment]
Hey,

thanks  for replying. I wrote this not-nice but working Dockerfile:

```
FROM almalinux
ARG VERSION=3.0.2
RUN dnf update -y
RUN dnf groupinstall -y "Development Tools"
RUN dnf install -y epel-release
RUN dnf update -y
RUN dnf install -y bzip2 git pigz gzip wget pbzip2
WORKDIR /usr/local/src
RUN wget https://github.com/HorizenOfficial/zen/archive/refs/tags/v${VERSION}-bitcore.tar.gz -O /usr/local/src/zen-${VERSION}.tar.gz
RUN tar xzf /usr/local/src/zen-${VERSION}.tar.gz
RUN rm /usr/local/src/zen-${VERSION}.tar.gz
WORKDIR /usr/local/src/zen-${VERSION}-bitcore/zcutil
RUN ./build.sh --legacy-cpu -j 8
VOLUME "/zen"
RUN /bin/cp /usr/local/src/zen-${VERSION}-bitcore/src/zend /zen/
RUN /bin/ln -s /usr/local/src/zen-${VERSION}-bitcore /usr/local/src/zen
RUN /usr/bin/strip -sx /usr/local/src/zen-${VERSION}-bitcore/src/zend /usr/local/src/zen-${VERSION}-bitcore/src/zen-cli
ENTRYPOINT ["/bin/cp", "/usr/local/src/zen/src/zend", "/usr/local/src/zen/src/zen-cli", "/zen/"]
```

Which works flawles. Wait, wait? Yes, it does. I can reproduce the error on a clean installation in a clean vm (failing) but its working in docker. Both systems have a different cpu tho. One (vm) needs legacy-cpu, the other (docker) does not. I will try running the docker file on the legacy-cpu server and report.

**Comment by christianreiss** [comment]
No, the docker-file runs perfectly fine on any vm or baremetal I throw it at. Running pretty much the same commands in a fresh installation fails, tho.

**Comment by lander86** [comment]
Hello @christianreiss ,

i've tried to reproduce the issue with an AlmaLinux 8.5 VM.
The kernel version was 4.18.0-348.2.1.el8_5.x86_64
gcc version 8.5.0 20210514 (RedHat 8.5.0-4)
CPU : SkyLake (Cofee lake)
Ram : 16Gb

I've not encountered any issue during the build. Could you please tell me how have you installed the dependencies ? Maybe it could be related to something missing or to awrong version of one of the dependecies. 

Thanks

**Comment by christianreiss** [comment]
I will keep debugging this on my end. The fact that neither you nor the Dockerfile could force the issue is odd.
I will close this ticket; if the issue is found to be upstream I will re-open this ticket again.

**Comment by lander86** [comment]
Thank you for the feedback. I'm then going to close this ticket. 
Please feel free to re-open it should you need further support or should you discover anything new.
