### ISSUE TITLE
You all broke mining with 3.X version

### ISSUE THREAD

**Issue by g00dnatur3** [HorizenOfficial/zen#428]
before the 3.0 change, mining was cool, i was mining blocks for YEARS no problem

now i cant mine ANY blocks.. i get this error

2021-12-01 11:33:53 [Pool]	[horizen] (Thread 3) rpc error with daemon instance 0 when submitting block with submitblock {"code":-22,"message":"Block decode failed"}

i even tried deleting my blockchain and had it completely re-download and sync... and STILLL i have this issue

what did you change to break mining?

everything was working fine before...

Thanks for you help in advance...

**Comment by lander86** [comment]
Hello @g00dnatur3,

with 3.X release we've introduced some important changes and upgrades. 
Have you already read the guide we created for mining ? 
[Zend to Zendoo upgrade ShortGuide v1.4 – Mining Pools](https://downloads.horizen.io/file/web-assets/Zend_to_Zend_oo_Mining_Pools_v1.4.pdf)
I suggest to take a look in particular to the section "Typical steps needed to forge a block".

You can also take a look to the post in which we announced the changes for further informations : 
https://blog.horizen.io/mandatory-software-upgrade-zen-3-0-0/

Please let us know if the guide is clear and if you will be able to mine blocks again.

**Comment by g00dnatur3** [comment]
Hi,
i got it working again, sorry for getting a little upset, but you messing with my money yo :)

i installed your latestest binary for legacy cpu, re-synced the blocked chain from scratch, and installed your version of the stratum pool found here: `HorizenOfficial/node-stratum-pool`

thanks for your help.

**Comment by lander86** [comment]
Hi @g00dnatur3,

i'm happy to hear that everything is back to work and that the issue is now solved. 
No worries, we're happy to help.
