### ISSUE TITLE
tls_cert_verified: false Zen Super Node

### ISSUE THREAD

**Issue by ghost** [HorizenOfficial/zen#438]
### Describe the issue
A Zen super nodes TLS certificate is not valid anymore out of the blue five days ago. No changes were done to the server since the 3.0.3 update.

There is no useful information to be found in the logs. 

Super node tracker says: "certificate has expired"

In the debug.log multiple messages are seen as the node connects:
TLS: connection to [hidden]:9033 has been established (tlsv = TLSv1.3 0x0304 / ssl = OpenSSL 1.1.1l  24 Aug 2021 0x101010cf ). Using cipher: TLS_AES_256_GCM_SHA384

...indicating that the TLS connections are being established.

No errors seen in the logs.

#### If so, please list the steps to reproduce below:
No, Super node was running fine, now it doesnt. I only have one Super node, can not reproduce this.

### Expected behaviour

Certificate should be valid. 

"zen-cli getnetworkinfo" should return "tls_cert_verified: **true**"

### Actual behaviour + errors
"zen-cli getnetworkinfo"  returns "tls_cert_verified: **false**"

### The version of Zen you were using:
Zen Daemon version v3.0.3-bitcore

### Machine specs:
- OS name + version: Ubuntu Server 20.04
- CPU: Xeon 8-core
- RAM: 16GB
- Disk size: 2TB
- Disk Type (HD/SDD): SSD
- Linux kernel version (uname -a): 5.4.0-100-generic
- Compiler version (gcc -version): gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0

### Any extra information that might be useful in the debugging process.

Attempted so far:
1. renew certificate via certbot (although it was not due for renewal). 
2. delete certificates (certbot delete) and aquire a new one following: [https://horizenofficial.atlassian.net/wiki/spaces/ZEN/pages/136871977/Part+6+-+Procure+and+Configure+Certificate](url)
3. Tried to do this fix: [https://zen-solutions.io/how-to-fix-r3-expired-lets-encrypt-certificates-on-nodes/](url)
4. Reboot the server

**Comment by ptagl** [comment]
Hi @krilson, sorry for the late reply. I guess it might have been a temporary issue and it's been solved now. If that's the case, feel free to ignore my answer and I'll be closing the issue in the next few days. On the other hand, if it's still actual, may you please directly contact our Support Center on Discord? Our colleagues will be able to help you out!

**Comment by joesixpack** [comment]
Seeing this on 3.1.0 and it has not been resolved for last 17 days.  Certificate isn't due to expire until next month.

A restart fixed it.  Annoying.

**Comment by ptagl** [comment]
Hi @joesixpack, thanks for reporting, we'll resume the investigation of this issue given the new details you provided.

**Comment by psyraxaus** [comment]
There are a couple of common causes for the zend daemon still using an expired cert.  

The first is because the zend daemon was started manually and the services that are created during the node install guide to renew the cert was not able to restart the zend daemon using the systemd service.

The second is if the cert itself has not been renewed because of an issue with the certbot renewal service.

If the issue persists when the next cert renewal occurs, please come onto discord and I will be able to investigate with you what is going on with your services.

My name on discord is 
psyrax | Doesn't DM Support

**Comment by joesixpack** [comment]
Happened again two weeks ago.  Had to restart zend so it would recognize the certificate as valid again.  Certificate does not expire until Oct -- same as last time.  Just upgraded to zen 3.2.0 via apt but noticed the daemon didn't restart as the new version as expected. 🤔

**Comment by psyraxaus** [comment]
> Happened again two weeks ago. Had to restart zend so it would recognize the certificate as valid again. Certificate does not expire until Oct -- same as last time. Just upgraded to zen 3.2.0 via apt but noticed the daemon didn't restart as the new version as expected. 🤔

That means that the services that were created during the initial setup for the supernode are not running correctly and restarting the zend daemon when the cert is renewed.

What is your linux flavour and version?
Please run `lsb_release -a`

And post the output, or if you would like to work through this issue in real time, please head over to our Discord server and look me up in the node support channel

**Comment by joesixpack** [comment]
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

I'll take a look at the startup services.  I did notice theres no file in /etc/systemd/system so maybe its in the system directory which I can't remember the path of atm.

**Comment by joesixpack** [comment]
I converted over to the snap version of certbot and updated the appropriate service file.  I bet that will do the trick!

**Comment by AndreaLanfranchi** [comment]
Closing as stale since long time now.
Feel free to reopen or add comments if needed
