### ISSUE TITLE
Zend runs without config file

### ISSUE THREAD

**Issue by tarrenj** [HorizenOfficial/zen#44]
Previously, if a user would start `zend` without a config file, it would copy the config file and exit. Now `zend` will run fine without a config file:
https://github.com/ZencashOfficial/zen/blob/master/src/bitcoind.cpp#L104

ZCash 1.0.14 still uses the same warning from when we originally forked:
https://github.com/zcash/zcash/blob/v1.0.14/src/bitcoind.cpp#L104

**Comment by tarrenj** [comment]
Apparently, this is intended behavior: https://github.com/ZencashOfficial/zencash/blob/development/src/util.cpp#L635

This was done in a commit for `Integrated Commit Update folder locations - 03/04/2017`.

**Comment by cronicc** [comment]
Side effect of this is that the default config file is never copied because this catch never fires https://github.com/ZencashOfficial/zencash/blob/18f352a3bad646d887909acb49c40cb01eeec042/src/bitcoind.cpp#L111

People might be relying on the config being copied on first run in auto setup scripts.

**Comment by tarrenj** [comment]
Closed in https://github.com/ZencashOfficial/zencash/commit/7f45fcfc3fcc9b371da7e899d4ad12c51a522a71
