### ISSUE TITLE
zend: wallet/wallet.cpp:709 ... failed

### ISSUE THREAD

**Issue by minzak** [HorizenOfficial/zen#449]
On the Zen 3.1 and 3.0.3 I sometimes got errors and after that daemon exited (and service restart it) and it is all cycled.
```
zend: wallet/wallet.cpp:709: void CWallet::IncrementNoteWitnesses(const CBlockIndex*, const CBlock*, ZCIncrementalMerkleTree&): Assertion `(nd->witnessHeight == -1) || (nd->witnessHeight == pindex->nHeight - 1)' failed.
Rescanning last 1104304 blocks (from block 17498)...
init message: Rescanning...
wallet 344484ms
```
How to correct resolve it?
Or in this place need bug fix?

Thanks.

**Comment by minzak** [comment]
https://github.com/HorizenOfficial/zen/issues/344

Same solutions?
What is the best way? rescan wallet or run with fresh chaindata?

**Comment by ptagl** [comment]
Hi @minzak, removing the chain data and starting from scratch would probably work but it takes a lot of time.

I suggest you to try the following steps as a quicker workaround (assuming that you Zen data folder is `~/.zen`):

1. Rename "blocks" and "chainstate" folders `mv ~/.zen/blocks ~/.zen/blocks_backup; mv ~/.zen/chainstate ~/.zen/chainstate_backup`
2. Run zend to remove all wallet transactions and requesting a rescan `zend -zapwallettxs=1 -rescan`. Wait for rescan to finish (will be quick), then stop zend
3. Restore the "blocks" and "chainstate" folders `rm -r  ~/.zen/blocks  ~/.zen/chainstate; mv ~/.zen/blocks_backup ~/.zen/blocks ~/.zen/chainstate_backup ~/.zen/chainstate`
4. Run a fast reindex `zend -reindexfast`. It usually takes hours, depending on your machine. When completed, everything should work properly.

Please, let me know if it works or if you need any further assistance.

**Comment by minzak** [comment]
Hi @ptagl just need some clarifications in steps.

In 2 steps what will be with the wallet - I think after that balance will be 0 because no chains with transactions and hashes to calculate the final balance. What is lefts from the wallet after that step?

Step 2 needed for chaindata? But that data is needed format and data. Also, I can quickly restore a valid chain from the "reference" node. Does it help me? Or it is steps needed only for the wallet?

Thanks.

**Comment by ptagl** [comment]
Yes, after step 2 the wallet will be "empty" due to `-zapwallettxs`, so zend would need to sync all the blocks to restore the right wallet balance.

Since syncing from network would take days, I suggested to restore the previous blockchain data (step 3) and then request a fast reindex so that the wallet cache can be rebuilt in the proper way.

Currently wallet cache of notes (shielded amounts) is the issue: all of them are in the wallet, but the cache is missing some mandatory information needed to spend them, so the only way to fix is to get rid of that cache (step 2) and then built it from scratch (step 4).

**Comment by minzak** [comment]
Still testing this way, but messages like:
`LoadBlocksFromExternalFile: Processing out of order header, child 000000008c1a6329e7de36077a6e7d1710ce99226f0284c212e39bbbac58ed80 of 00000000745aabc84e10f27083eb2b281b376e0479fefb796ff63d22d8e7f567`

Still Appears a long time. More than 10h

> 
> [zend] Wiping LevelDB in /home/zen/.zen/blocks/index
> ...
> [zend] Wiping LevelDB in /home/zen/.zen/chainstate
> ...
> [zend] Removing sidechains files [CURRENTLY ALL] for -reindex. Subfolders untouched.
> ...
> [zend] Reindexing block file blk00000.dat, headers-only...
>  ...
> [zend] LoadBlocksFromExternalFile: Processing out of order header, child 0000dc0ee8d551a3979d2f15f1b6edcdd6800a5062f1acd02bd4d9e434934e7a of 00012456ce1d22b1976dfd0aa543add1c8a1c105894f18c4498fc76a2c8a59e0

And chainstate folder was wiped - it is normal?

**Comment by minzak** [comment]
Hm, my current quick way is:

1. Remove DB CHain
2. Run node with -zapwallettxs=1 -rescan
3. Restore DB Chain
4. Run node with -rescan

It is more quickly, against making some changes in DB Chain.
I hope It is will be enough to never see strings with wallet.cpp )
