### ISSUE TITLE
fix metrics

### ISSUE THREAD

**Issue by pierstab** [HorizenOfficial/zen#46]
fix metrics subsidy

**Comment by pierstab** [comment]
close by [https://github.com/ZencashOfficial/zencash/pull/48](url)

**Comment by tarrenj** [comment]
FYI: You can say "Closes #46" in https://github.com/ZencashOfficial/zencash/pull/48 to automatically close this issue when that PR gets merged.  Might save you some time in the future :)

See: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by pierstab** [comment]
@tarrenj  right
