### ISSUE TITLE
Innaccurate params size still reported (zcutil/fetch-params.sh)

### ISSUE THREAD

**Issue by AndreaLanfranchi** [HorizenOfficial/zen#468]
Booting  a node requires download params. [Reported estimate size of download is, at current figures, inaccurate](https://github.com/HorizenOfficial/zen/blob/master/zcutil/fetch-params.sh#L239): 911MB.
Just started a node and this actual size:

```
1.6G    ./.zcash-params
```

Zen Daemon version v3.1.0 on Linux

**Comment by JackPiri** [comment]
Addressed by https://github.com/HorizenOfficial/zen/pull/622.
