### ISSUE TITLE
sender's zen is disappeared

### ISSUE THREAD

**Issue by yangchou19** [HorizenOfficial/zen#482]
This issue tracker is only for technical issues related to Zen.

General Zen questions and/or support requests are best directed to the [Discord](https://horizen.io/invite/discord), or [Support Portal](https://support.horizen.io).

For reporting security vulnerabilities or for sensitive discussions with our security team, please see the [Bug Bounty Policy and Scope](https://horizenofficial.atlassian.net/wiki/spaces/ZEN/pages/136871957/Bug+Bounty+Submission+Policy+and+Scope), or send an encrypted email to security@horizen.io with information. The public key for that address is available [here](https://HorizenOfficial.github.io/keys/).

### Describe the issue
I deployed zen full nodes on linux, but when I initiated a transaction on the node, the sender's money was all gone and automatically redirected to an untractable address.

### Can you reliably reproduce the issue?
yes
#### If so, please list the steps to reproduce below:
1. chose a sender and receiver
2. make a normal transaction

### Expected behaviour
the transaction can be made correctly 

### Actual behaviour + errors
the sender's Horizen is disappeared

**Comment by AndreaLanfranchi** [comment]
Please help us to better understand the problem.
- you say you have deployed a full node on Linux: can you clarify if it was a test node or a main chain node ? Also was it in sync ? Can you share the exact command (with all arguments) you use to start the node ? And finally :  the node you're running is built by you from source code or you have downloaded the binary executable from somewhere?
- when you say you started a transaction from a sender to a receiver how did you do that? Using a wallet or from rpc ? Can you share the step by step actions you performed so we can try reproduce the problem?
- when you say sender Horizen is gone what do you mean ? Do you see the transaction on a block explorer?

Thank you for your help

**Comment by yangchou19** [comment]
Thank you for your answer, I will try my best to describe the problem.
1. I deployed a full node on Linux and it was a main chain node. And I build it from source code. I just use ./src/zend and create my zend.conf to run the node.
2. when I started the transaction from a sender to a receiver, I use zen-cli command `./zen-cli  z_sendmany sender '[{"address": "receiver", "amount": 0.003}]' `, and I get the opid, it was success. when I use zen-cli command `./zen-cli z_getbalance receiver ` , the balance is 0.000; I also use rpc, it appeared the same problem.
3. I see the block explorer, I find the zen is also at the node's wallet, but I can not use `./zen-cli list addresses` to find it, but I can use `z_sendmany` to start a transaction.
And there are pictures about it:
### The balance is 0.998 before I start a transaction.
<img width="183" alt="image" src="https://user-images.githubusercontent.com/49429748/197466263-cfbf4ad2-d5e7-4528-a49e-08a7c608330b.png">
<h3> use zen-cli start a transaction</h3>
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/49429748/197465993-be95e773-2090-40ae-a6e7-dcdcdde9ae43.png">
<h3>zen is gone after I finished a transaction</h3>
<img width="741" alt="image" src="https://user-images.githubusercontent.com/49429748/197466080-04fb9844-b921-4832-a212-a21173a9e912.png">
<h3>zen is gone to another address</h3>
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/49429748/197467405-3cf0eea6-88ff-4b21-95e7-bf93876cec84.png">

**Comment by AndreaLanfranchi** [comment]
Thank you @yangchou19,
this is valuable info.  Please allow us to try reproduce the issue locally.
We'll be back to you.

**Comment by ptagl** [comment]
Hi @yangchou19, there are at least a couple of things to clarify here:

1. The RPC command `z_sendmany` has an optional boolean parameter `sendChangeToSource` that is false by default. This means that whenever you have a **change** generated by this RPC command, the related output is **sent to a different address** to preserve privacy.  If you want the change to go to the same address that is sending coins, you have to explicitly set `sendChangeToSource` to true.

2. Given that your change is now available on a different address, I guess that your call to `z_getbalance` is returning a zero value because you are passing the source address instead of the **newly generated change address**. If you use the right address, it must show 0.9949 as expected. Alternatively, you can try to use `z_gettotalbalance` to get the cumulative amount available on all addresses managed by your wallet, `listunspent` to get the list of all UTXOs available and `listaddressgroupings` to check all the addresses available.

Let us know if you need further assistance!

**Comment by yangchou19** [comment]
> 嗨@yangchou19，这里至少有几件事需要澄清：
> 
> 1. RPC命令`z_sendmany`有一个可选的布尔参数`sendChangeToSource`，默认为false。这意味着，每当您使用此RPC命令生成**更改**时，相关输出都会**发送到另一个地址**以保护隐私。如果您希望更改发送到发送硬币的同一地址，则必须显式将`sendChangeToSource`设置为true。
> 2. 鉴于您的更改现在可以在另一个地址上使用，我猜您对`z_getbalance`的调用将返回零值，因为您传递的是源地址而不是**新生成**的**更改地址**。如果您使用正确的地址，它必须正常显示0.9949。或者，您可以尝试使用`z_gettotalbalance`来获取钱包管理的所有地址的累计可用金额，`listunspent`以获取所有可用的UTXO列表，`listaddressgroupings`以检查所有可用的地址。
> 
> 如果您需要进一步的帮助，请告诉我们！

Thank you for Patience and your help, Your advice helped me to solve the problem😊.  I use the `z_gettotalbalance` get  the cumulative amount available on all addresses.
