### ISSUE TITLE
After restart my horizen node, command`z_listoperationids` returned null.

### ISSUE THREAD

**Issue by yangchou19** [HorizenOfficial/zen#488]
### Describe the issue
I just restarted the Horizen node today, when I used the command `./zen-cli z_listoperationids`, but it return nothing. Before I restarted it , I use it and will return some opid.

#### If so, please list the steps to reproduce below:
1. I deployed a full node on Linux and it was a main chain node. And I build it from source code. I just use ./src/zend and create my zend.conf to run the node.
2. when I restarted the node,  I use zen-cli command  `./zen-cli z_listoperationids`. I got no opid.

### Expected behaviour
when I use zen-cli command  `./zen-cli z_listoperationids`, it will return the opid that I generated.

### Actual behaviour + errors
when I use zen-cli command  `./zen-cli z_listoperationids`, it return null.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/49429748/200170837-ec95805b-339a-4103-80f4-0eea952c6a39.png">

### The version of Zen you were using:
 v3.2.0

**Comment by JackPiri** [comment]
List of operations ids is not persistent, it's just in-memory data: hence, when restarting the node, it gets reinitialized as empty.
