### ISSUE TITLE
How can I use zen-cli to create a new account?

### ISSUE THREAD

**Issue by yangchou19** [HorizenOfficial/zen#492]
### Describe the issue
I want to know how can I use zen-cli to create  a new account? I use `zen-cli -help`, but I didn't find any command to create a new account. Did anyone know it. 

### The version of Zen you were using:
v3.2.0

**Comment by JackPiri** [comment]
Being built on a utxo-model, zend has no notion of accounts; please consider methods `getnewaddress`/`z_getnewaddress `for creating new transparent/shielded addresses.
