### ISSUE TITLE
Mac OS build doesn't work - Proton

### ISSUE THREAD

**Issue by LukasBures** [HorizenOfficial/zen#57]
Mac OS build doesn't work, tested on Mac OS HS 10.13.5

```
-- Build type is "RelWithDebInfo" (has debug symbols)
-- PN_VERSION: 0.17.0 ()
CMake Error at proton-c/CMakeLists.txt:182 (message):
  No atoll API found
```

related to: `--enable-proton`

In Zcash upstream they have dropped support for other than Linux binaries.

**Comment by cronicc** [comment]
Build does work with [ZencashOfficial/zencash-apple](https://github.com/ZencashOfficial/zencash-apple) with proton disabled, which is the default.
