### ISSUE TITLE
Upgrading zen 4.1 does not work on debian bookworm via apt.

### ISSUE THREAD

**Issue by monikrk** [HorizenOfficial/zen#607]
### Describe the issue

Upgrading zen 4.1 does not work on debian bookworm via apt.

root@XXX:~# systemctl start zend.service 
Job for zend.service failed because a timeout was exceeded.
See "systemctl status zend.service" and "journalctl -xeu zend.service" for details.

The service definition file.

cat /lib/systemd/system/system/zend.service 
[Unit]
Description=Zen daemon

[Service]
User=zen
Type=forking
ExecStart=/usr/bin/zend -daemon -pid=/home/zen/.zen/zend.pid
PIDFile=/home/zen/.zen/zend.pid
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target

The log file shows no new lines.

It is solved by reverting to version 4.0.

### Can you reliably reproduce the issue?

Update from apt:

apt upgrade

Stop service

Start service and...

Job for zend.service failed because a timeout was exceeded.
See "systemctl status zend.service" and "journalctl -xeu zend.service" for details.

### The full version of `zend` you are using

v4.1

### Machine specs

- OS name and version:  GNU/Linux bookworm
- CPU:  Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz
- RAM: 16GB
- Disk size: 1TB
- Disk type (HD/SDD): HD
- Linux kernel version (uname -a):  Linux machine 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux
- Compiler version (gcc -version): gcc (Debian 12.2.0-14) 12.2.0

**Comment by psyraxaus** [comment]
From my cursory search of your CPU it doesn't look like it supports the newer instruction sets and may need the legacy CPU binary.

What is the output of this command?
`( grep -q "adx" /proc/cpuinfo && grep -q "bmi2" /proc/cpuinfo ) && echo "APT binary" || echo "Legacy CPU binary required"
`

**Comment by monikrk** [comment]
This is correct. Installing the legacy version works correctly.
Thank you

**Comment by monikrk** [comment]
Resolved.
