### ISSUE TITLE
[Security Node] IP6 <ipv6> from zend does not match DNS IP6 (not found) for <domain>

### ISSUE THREAD

**Issue by msamesch** [HorizenOfficial/zen#609]
### Describe the issue

Since I updated my system (and zen to 4.1) I get the following compliance exception in the tracking system

> IP6 (<my_ip6>) from zend does not match DNS IP6 (not found) for <my_domain>.

How can I fix this?

### The full version of `zend` you are using

v4.1.0

### Machine specs

- OS name and version: Linux 5.10.0-25-amd64
- CPU: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
- RAM: 8 Gb
- Disk size: 140 Gb
- Disk type (HD/SDD): HDD
- Linux kernel version (uname -a): Linux 5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux
- Compiler version (gcc -version):  (Debian 10.2.1-6) 10.2.1 20210110

**Comment by AndreaLanfranchi** [comment]
Hi @msamesch,
I see the issue is long standing. Sorry for that.
Do you have any update on this ? Have you managed to solve it ?
Do you still need assistance ?

**Comment by msamesch** [comment]
Hi @AndreaLanfranchi,
Thanks for your reply.
I postponed further attempts to solve the problem and therefore haven't checked the situation for some time. To my surprise, the error disappeared silently, for whatever reason (at least without any changes to my server). :smile: 
As for now everything seems fine.

**Comment by AndreaLanfranchi** [comment]
Happy to hear good news.
Feel free to reach out again if anything else.
Have a good day.

**Comment by msamesch** [comment]
Thanks. Have a good day too.
