### ISSUE TITLE
build ./zcutil/build.sh --legacy-cpu failed

### ISSUE THREAD

**Issue by szhelonkin** [HorizenOfficial/zen#610]
### Describe the issue

failed loading gmp-6.2.1.tar.bz2

### The full version of `zend` you are using

4.1.0

### Machine specs

- OS name and version: 
- CPU: 
- RAM: 
- Disk size: 
- Disk type (HD/SDD): 
- Linux kernel version (uname -a): 
- Compiler version (gcc -version):

**Comment by AndreaLanfranchi** [comment]
Hi @szhelonkin,
I see the issue has been here for a while. Sorry for that.
Have you solved the problem ?

If not ... please is essential to know more info about the environment you're using to build zen.

Which computer type ?
Which Operating System ? If Linux which distribution ?
What version of compiler are you using ? GCC or Clang ?
Thank you in advance for your replies
