### ISSUE TITLE
debug.log Whitespace before and after `Zcash version. . .`

### ISSUE THREAD

**Issue by tarrenj** [HorizenOfficial/zen#72]
![unknown](https://user-images.githubusercontent.com/3710484/41693553-cf92da0e-74d3-11e8-9469-f8c86ba269ef.png)

Might be fixed, or at least effected by https://github.com/ZencashOfficial/zen/pull/66

**Comment by tarrenj** [comment]
A PR resolving this issue would be quickly merged.

**Comment by hellcatz** [comment]
The above reference PR fixes the "ZCash" label, but may not 100% close this issue.
See below for further explanation of why the "extra spaces before and after" is happening.

Culprit lines of code: 

      Stock: https://github.com/ZencashOfficial/zen/blob/master/src/init.cpp#L827-L828
      Extra-dup: https://github.com/ZencashOfficial/zen/blob/master/src/init.cpp#L1116-L1119

I think the idea is, if the debug file is "shrunk" to tag the debug.log file with the zen info again.
However, the code is not accomplishing this properly; resulting in the "extra white spaces before & after".

We could remove the "extra-dup" lines. This would result in a "shrunken" debug.log file potentially not having the zen info present. Same behaviour as zcash's code base. https://github.com/zcash/zcash/blob/master/src/init.cpp#L1176-L1181

Or, remove the "stock" lines. This would result in the debug.log file potentially not having the "Zen v..." tag in case of early startup errors in init.cpp

Open to suggestions.

**Comment by hellcatz** [comment]
The latest PR https://github.com/ZencashOfficial/zen/pull/99 removes the extra white spaces "after".
We most likely want to keep the "before" whitespaces as an indication of Zen daemon restarting in the log.
