### ISSUE TITLE
zend sometimes warns of 0 blocks received in the last 4 hours during initial sync

### ISSUE THREAD

**Issue by tarrenj** [HorizenOfficial/zen#74]
Original issue: https://github.com/ZencashOfficial/zen_archived/issues/138

**Comment by tarrenj** [comment]
This is still an issue, but purely a cosmetic one.

**Comment by DZFLUX** [comment]
Is this still a item we want a noob to look at? Seems kind of old

**Comment by ptagl** [comment]
Fixed with release [3.2.0](https://github.com/HorizenOfficial/zen/releases/tag/v3.2.0).
