### ISSUE TITLE
Update to libsodium 1.0.15

### ISSUE THREAD

**Issue by tarrenj** [HorizenOfficial/zen#77]
Original Issue: https://github.com/ZencashOfficial/zen_archived/issues/129

Libsodium 1.0.11 leads to a dead link, this hasn't affected us because of our depends mirror.
See zcash/zcash#2693, we should pull in zcash/zcash#2763, change links to our mirror and upload the package there.

And while we're at it also update other dependencies as long as they don't cause any issues while we're still behind upstream.

**Comment by cronicc** [comment]
Fixed in 2.0.14
