### ISSUE TITLE
CA Cert exception false - getinfo shows cert value TRUE

### ISSUE THREAD

**Issue by tarrenj** [HorizenOfficial/zen#78]
Original Issue: https://github.com/ZencashOfficial/zen_archived/issues/103

Completed setup of the secure node on mainnet and receiving an out of compliance with the tracker.

Zen Tracking System Exception: "cert: could not validate the SSL certificate."

TLS cert reports as valid however the tracker states the node is out of compliance.

The 'transparant' balance for the 42 zen is on a transparent address on swing wallet.

I've re deployed and rebuilt node several times using a hosted VPS. Each time yielding the same outcome. 

Cross referenced install using various guides however used the following guide for setup:
https://blockoperations.com/how-to-build-and-operate-a-zencash-secure-node/#securenodetracker

$ zen-cli getnetworkinfo | grep true
  "tls_cert_verified": true,
      "reachable": true,
      "reachable": true,
      "limited": true,

 zen-cli getinfo
{
  "version": 2001051,
  "protocolversion": 170002,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 230758,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 573473.63484937,
  "testnet": false,
  "keypoololdest": 1514523794,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": ""
}

zen-cli z_gettotalbalance
{
  "transparent": "0.00",
  "private": "1.2498",
  "total": "1.2498"
}

**Comment by ADumaine** [comment]
You are using an old version of zen  "version": 2001051, which is 2.0.10 and is now 2 behind.

A new version was just released, please follow steps 1-4 of the guide:
https://documentation.zencash.com/display/ZEN/Upgrading+Secure+Node+Software

Also make sure you have port 9033 open for inbound connections to zen. I only see 8 connections which may indicate you only have outbound connections.  The tracking server uses an inbound connection to test the certificate by fqdn.

**Comment by tarrenj** [comment]
Going to close this issue, as it's likely stale.  Please reopen if anyone runs into this problem again.
