### ISSUE TITLE
Memory should be freed after SecureNode challenge is complete

### ISSUE THREAD

**Issue by tarrenj** [HorizenOfficial/zen#82]
Original Issue: https://github.com/ZencashOfficial/zen_archived/issues/86

I initially posted this in the [secnodetracker ](https://github.com/ZencashOfficial/secnodetracker/issues/6) github but was asked to post it here instead.  

I have a 2GB Linode with 4GB of swap and I kept getting exceptions so when I checked and zend was using a massive amount of memory (RAM & Swap) whilst it was just sitting there idle.

![image](https://user-images.githubusercontent.com/7847340/32561996-81cfb802-c4a5-11e7-8a64-d98b7cd4c050.png)

I restarted zend but when it came back up it was using the same amount of memory. I then stopped both zend and the tracker then started them in the same order and now the memory useage is back to an acceptable level

![image](https://user-images.githubusercontent.com/7847340/32547021-c4113d6c-c478-11e7-9a9c-aac868c2fd82.png)

So when the next challenge was run the Memory usage jumped back up as expected but stayed there long after the challenge finished.

![image](https://user-images.githubusercontent.com/7847340/32562175-e55f5d46-c4a5-11e7-914e-83cfff4eaca7.png)

![image](https://user-images.githubusercontent.com/7847340/32562194-ece3d844-c4a5-11e7-8f67-129e9c0f6663.png)

This is my node on the [tracking ](https://securenodes.eu.zensystem.io/nodes/262/detail) site, both the wallet and tracking software are the latest version (zen: 2001050     tracker: 0.0.8).

I'm waiting for the next challenge to see if it happens again, I'll update here when it does..

**Comment by tarrenj** [comment]
This is not strictly for Secure/Super Nodes, and effects any shielded transaction processing.

**Comment by bedeabza** [comment]
This is still the case in version 2.0.14. Will it be fixed in 2.0.15?

The effect it has is running a second benchmark on a 2GiB physical RAM + 2GiB swap fails: `zen-cli zcbenchmark createjoinsplit 1`

This can become a serious issue in running a secure node since the only way to work around it is to restart the daemon after the challenges.

**Comment by tarrenj** [comment]
This was not fixed in 2.0.15.  I'm applying the hacktoberfest label in the hopes that someone takes a stab at it!

**Comment by mauriziobinello** [comment]
Expected improvements with Sapling
