### ISSUE TITLE
OpenSSL integration

### ISSUE THREAD

**Issue by tarrenj** [HorizenOfficial/zen#85]
Original Issue: https://github.com/ZencashOfficial/zen_archived/issues/26
The branch `TLS_integration` doesn't exist in the new repo.

Branch `TLS_intergration` has a working implementation using self signed certificates. 
Todo:

- [x] allow user to chose certificates
- [ ] allow user to choose to connect to only TLS enabled nodes
- [x] connect to only TLS enabled nodes with CA signed certificates
- [ ] after making sure most of the network is TLS enabled, disconnect non-TLS nodes unless user allows unencrypted connections

**Comment by tarrenj** [comment]
Hush issue: https://github.com/MyHush/hush/issues/63
Hush PR: https://github.com/MyHush/hush/pull/68

**Comment by AndreaLanfranchi** [comment]
Closing as TLS implementation is covering most of the netwok.
Further dicussions about whether to allow unencrypted transactions will follow in other tickets.
