### ISSUE TITLE
`Bitcoin Core` used in error message string

### ISSUE THREAD

**Issue by tarrenj** [HorizenOfficial/zen#92]
https://cdn.discordapp.com/attachments/334085157441110017/464114926248787979/Screen_Shot_2018-07-04_at_10.06.02_AM.png

**Comment by hellcatz** [comment]
If my commit above looks good, I can do a PR. Enjoy!

**Comment by hellcatz** [comment]
Resolved in https://github.com/ZencashOfficial/zen/pull/99 and https://github.com/ZencashOfficial/zen/pull/66
