### ISSUE TITLE
Add HF blocks as checkpoint blocks 

### ISSUE THREAD

**Issue by cronicc** [HorizenOfficial/zen#93]
The testnet HF block 260500 and upcoming mainnet HF block 344700 should be added to zend as checkpoint blocks. 
Procedure: https://github.com/ZencashOfficial/zen/blob/63e1f4ce04c20788750a03d51e49c00c67b956f7/src/chainparams.cpp#L170-L174

**Comment by tarrenj** [comment]
https://github.com/ZencashOfficial/zen/tree/checkpoints adds checkpoints for mainnet and testnet.  Just waiting on mainnet node to finish syncing past the HF block as a test before submitting the PR.
